import Head from 'next/head';
import Hero from '../components/Hero';
import Section_1 from '../components/Section_1';
import Section_2 from '../components/Section_2';
import Section_3 from '../components/Section_3';
import Section_4 from '../components/Section_4';

export default function Home() {
  return (
    <>
      <Head>
        <title>Coach João André</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Section_1 />
        <Section_2 />
        <Section_3 />
        <Section_4 />
      </main>
    </>
  );
}
